# Generated by Django 5.2.17 on 2026-09-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="XrayAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="xrays/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Analyzed"),
                            ("unsupported_body_part", "Unsupported body part"),
                            ("models_not_trained", "Model not trained yet"),
                            ("error", "Error"),
                        ],
                        default="ok",
                        max_length=32,
                    ),
                ),
                ("body_part", models.CharField(blank=True, max_length=64, null=True)),
                ("body_part_confidence", models.FloatField(blank=True, null=True)),
                (
                    "abnormality_label",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("abnormality_confidence", models.FloatField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "X-ray analyses",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
